### ISSUE TITLE
Unable to decode the TiBlob object (purchase receipt)

### ISSUE THREAD

**Issue by raghuindra** [appcelerator-archive/ti.storekit#16]
After sucessfull purchase i have to send the purchase receipt to serevr for validation and server intern validate it from Apple.
i am reading the receipt from ti.Storekit.receipt parameter. and its returning TiBlob object.
can u tell me how to share this to server? can we convert this Blob into base64 string?

**Comment by chrisribe** [comment]
Hi Raghuindra,

I had the same issue the solution is to use this function.
var receiptB64String = Ti.Utils.base64encode(evt.receipt).text;

The thing that was not clear in my mind is that the receipt variable is an object and apple is EXPECTING the whole object to be base64 encoded to a string! They decode the string on their side and need ALL the object information.

Do not try to access and send the properties directly ("signature" , "purchase-info", etc). It will not work anyway, try Ti.API.INFO(evt.receipt.signature) just returns null (why I dont know...)

The ti.storekit SHOULD add this part in the example, it's simply missing. Validating on the server side is part of the process (in some cases). This would avoid confusion and wasted time.

Hope this helps.
Christian

References:
https://archive.appcelerator.com/question/156570/how-decode-purchase-info-from-storekit

**Comment by hansemannn** [comment]
Please check https://github.com/appcelerator-modules/ti.storekit/pull/17 which included the documentation changes requested.

**Comment by raghuindra** [comment]
Hi Guys, Thank you for your reply and support. I don't know what the real issue. Earlier even after passing the TiBlob to server the variable holding Blob object was always null. I am using Ti.Network.createHTTPClient and used to create a parameter object and adding it in the httpClient.send(params). Later i just though to put the TiBlob Object directly in the send method of HTTP Client like:
`httpClient.send({
		contractType:18,
		customerId: User.identifier,
		iosreceipt: Storekit.receipt,
	});`

Then on server, i am able to receive the ios receipt variable value with BLOB object in Server FILES variable access and there i sending the receipt by encoding it in base64 using PHP.
I am using PHP for server side scripting. 

`function verifyPurchase($sandbox=true) {
       $body = @file_get_contents($_FILES['iosreceipt']['tmp_name']);
 
            //encode receipt
            $body = base64_encode($body);
            $receipt = json_encode(array("receipt-data" => $body, "password" => "xxxxxxxxxxxxxxxxxxxx"));
            
            // NOTE: use "buy" vs "sandbox" in production.
            if ($sandbox) {
                $url = "https://sandbox.itunes.apple.com/verifyReceipt";
            } else {
                $url = "https://buy.itunes.apple.com/verifyReceipt";
            }
            
            //send receipt to Apple
            $curl_handle = curl_init();
            curl_setopt($curl_handle,CURLOPT_URL,$url);
            curl_setopt($curl_handle,CURLOPT_CONNECTTIMEOUT,2);
            curl_setopt($curl_handle,CURLOPT_RETURNTRANSFER,1);
            curl_setopt($curl_handle, CURLOPT_POSTFIELDS,$receipt);
            $buffer = curl_exec($curl_handle);
            curl_close($curl_handle);
        
            //getting answer from Apple
            $object = json_decode($buffer);
            $array = json_decode($buffer,true);
            print_r($array);
            //$status = $object->{'status'};
            
            
}

verifyPurchase(true);`

I got successful receipt validation from Apple server.

**Comment by hansemannn** [comment]
Well, there are different ways to solve this. If that works for you as well, that's fine! Can you test if everything works with the linked version? Would appreciate that!

**Comment by hansemannn** [comment]
For local validation, check #17 on how to troubleshoot possible issues.
