### ISSUE TITLE
Message when I launch build.py

### ISSUE THREAD

**Issue by jacklocke** [appcelerator-archive/ti.storekit#18]
First: I do not know much Python... maybe can be my fault...
I get this when I drag build.py on Python Launcher:
 `Last login: Fri Apr 29 09:41:05 on ttys003
MacBook-Jack:~ jack$ cd '/Users/jack/Downloads/ti.storekit-master/ios/' && '/usr/bin/pythonw'  '/Users/jack/Downloads/ti.storekit-master/ios/build.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/jack/Downloads/ti.storekit-master/ios/build.py", line 272, in <module>
    build_module(manifest,config)
  File "/Users/jack/Downloads/ti.storekit-master/ios/build.py", line 168, in build_module
    from tools import ensure_dev_path
ImportError: No module named tools
MacBook-Jack:ios jack$`

did I miss something?

**Comment by hansemannn** [comment]
Use `appc ti build -p ios --build-only` to build the module nowadays, thanks!
