### ISSUE TITLE
Receipt verification failed with Apple Server from ti.storekit

### ISSUE THREAD

**Issue by g33kme** [appcelerator-archive/ti.storekit#19]
Hello,

based on the apple forum, the InApp receipt verification failed. It seems that Apple changes some things to work no longer with the current ti.storekit (3.1.2) 

Have a look at the post:
https://forums.developer.apple.com/thread/47218

I tested the latest version of ti.storekit with Ti.SDK 5.2.2.GA, ios SDK 9.3 and Titanium Studio 4.5.0

The Storekit.validateReceipt() functions returns an "Invalid Receipt"

A fix for that would be very nice :)

Thanks,
Fab

**Comment by hansemannn** [comment]
See the linked PR for help to get it properly validated (last comment), thanks!
