### ISSUE TITLE
Missing to call Storekit.TRANSACTION_STATE_PURCHASED in transactionState eventListener.

### ISSUE THREAD

**Issue by sabir-qt** [appcelerator-archive/ti.storekit#21]
Hello Developer,

Thank you for developing this module.

I’m using your module in one of my applications. I’m facing a strange problem. When I get an alert of successful InApp Purchase I’m calling a function to post this payment on my custom server for maintaining records.
I’m calling this function in “transactionState” eventListener under Storekit.TRANSACTION_STATE_PURCHASED. My problem is that, sometimes my custom function does not invoke and sometimes it works great. Can you please find sometime and look into it. I’d be grateful.

My Code:

case storekit.TRANSACTION_STATE_PURCHASED:
    if (storekit.validateReceipt()) {
        Ti.API.info('My payment receipt : ' + JSON.stringify(evt.receipt.toString()));
        alert('Purchase completed!');
        evt.transaction && evt.transaction.finish();
        myFunction();
    }
break;

myFunction(){
console.log(“Posting my payment to my custom server”);
}

Thank you very much.

**Comment by hansemannn** [comment]
Here are the possible transaction states:
```objc
typedef NS_ENUM(NSInteger, SKPaymentTransactionState) {
    SKPaymentTransactionStatePurchasing,    // Transaction is being added to the server queue.
    SKPaymentTransactionStatePurchased,     // Transaction is in queue, user has been charged.  Client should complete the transaction.
    SKPaymentTransactionStateFailed,        // Transaction was cancelled or failed before being added to the server queue.
    SKPaymentTransactionStateRestored,      // Transaction was restored from user's purchase history.  Client should complete the transaction.
    SKPaymentTransactionStateDeferred NS_ENUM_AVAILABLE_IOS(8_0),   // The transaction is in the queue, but its final status is pending external action.
} NS_AVAILABLE_IOS(3_0);
```

Probably you are getting `SKPaymentTransactionStateDeferred` sometimes, which is not handled by the module so far. It is now exposed in the PR #17, check it out!
