### ISSUE TITLE
Needs support for restoreCompletedTransactionsWithApplicationUsername

### ISSUE THREAD

**Issue by bcpi** [appcelerator-archive/ti.storekit#6]
If possible, please add support for **restoreCompletedTransactionsWithApplicationUsername**, so restored purchases can be associated to an app's own user credentials. 

More info:

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html#//apple_ref/doc/uid/TP40008267-CH8-SW9

https://developer.apple.com/library/ios/documentation/StoreKit/Reference/SKPaymentQueue_Class/index.html#//apple_ref/occ/instm/SKPaymentQueue/restoreCompletedTransactionsWithApplicationUsername:

**Comment by hansemannn** [comment]
Please check https://github.com/appcelerator-modules/ti.storekit/pull/17 which included the new method `restoreCompletedTransactionsWithApplicationUsername` for you. Thanks! :rocket:
